import type { Metadata } from "next";
import Provider from "@/components/container/provider";
import Footer from "@/components/ui/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
        <div className="space-y-6">
        <Provider>
          {children}
        </Provider>
        <Footer />
        </div>
    </div>
  );
}
