import type { Metadata } from "next";
import "./globals.css";
import {Archivo,Poppins} from 'next/font/google'
import { ThemeProvider } from "@/components/ui/theme-provider";
import  { Toaster } from 'react-hot-toast';

const archivo = Archivo({
  weight : ["400","500","700",'900'],
  subsets:["latin"],
  variable: "--font-archivo",
})
const poppins = Poppins({
  weight : ["400","500","700",'900'],
  subsets:["latin"],
  variable: "--font-poppins",
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${archivo.variable} ${poppins.variable} antialiased `}
      >
        <ThemeProvider
           attribute="class"
           defaultTheme="system"
           enableSystem
        >
          <Toaster position="bottom-right" />
          {children}
          </ThemeProvider>
      </body>
    </html>
  );
}
