import type { Metadata } from "next";
import { auth } from "../lib/auth";
import { headers } from "next/headers";
import { redirect } from "next/navigation";
import Provider from "./provider/provider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };
export default async function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    
    const isAuth =await auth.api.getSession({
        headers : headers()
    })
    if(isAuth?.user.role !== 'admin'){
        redirect('/')
    }
  return (
    <div className="">

        <Provider>
        {children}

        </Provider>
    </div>
  );
}
