import type { Metadata } from "next";
import { auth } from "../lib/auth";
import { headers } from "next/headers";
import { redirect } from "next/navigation";
import Provider from "./provider/provider";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "@/app/api/uploadthing/core";
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };
export default async function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    
    const isAuth =await auth.api.getSession({
        headers : headers()
    })
    if(isAuth?.user.role !== 'admin'){
        redirect('/')
    }
  return (
    <div>
             <NextSSRPlugin
          /**
           * The `extractRouterConfig` will extract **only** the route configs
           * from the router to prevent additional information from being
           * leaked to the client. The data passed to the client is the same
           * as if you were to fetch `/api/uploadthing` directly.
           */
          routerConfig={extractRouterConfig(ourFileRouter)}
        />
        <Provider>
        {children}

        </Provider>
    </div>
  );
}
