import type { Metadata } from "next";
import Provider from "@/components/container/provider";
import Footer from "@/components/ui/footer";
import { auth } from "@/app/lib/auth";
import { headers } from "next/headers";
import { getUserPrefrences } from "../actions/preferences/preferences";
import { redirect } from "next/navigation";
import { prefenceRoute } from "@/constant/router";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await auth.api.getSession({
    headers : headers()
  })
  const userPrefrinces = await getUserPrefrences()
  if(user?.session){
    if(!userPrefrinces.length){
      return redirect(prefenceRoute)
    }
  }
  return (
    <div>
        <div className="space-y-6">
        <Provider>
          {children}
        </Provider>
        <Footer />
        </div>
    </div>
  );
}
